apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum23
  name: bookalbum23
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum23

