apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum233
  name: bookalbum233
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum233

