apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum233
  labels:
    app: bookalbum233
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum233
  template:
    metadata:
      labels:
        app: bookalbum233
    spec:
      containers:
      - name: bookalbum233
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
